## Numpy

Импортировать NumPy под именем np

In [3]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [4]:
np.full((10,1),2.5)

array([[2.5],
       [2.5],
       [2.5],
       [2.5],
       [2.5],
       [2.5],
       [2.5],
       [2.5],
       [2.5],
       [2.5]])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [11]:
a = np.zeros(10)
a[4] = 1

Развернуть вектор (первый становится последним)

In [13]:
b = np.random.rand(10,1)
print(b)
c = b[::-1]
print(c)

[[0.83120381]
 [0.53619401]
 [0.54974516]
 [0.14659329]
 [0.3471367 ]
 [0.8378274 ]
 [0.96348248]
 [0.13041367]
 [0.09347212]
 [0.3820891 ]]
[[0.3820891 ]
 [0.09347212]
 [0.13041367]
 [0.96348248]
 [0.8378274 ]
 [0.3471367 ]
 [0.14659329]
 [0.54974516]
 [0.53619401]
 [0.83120381]]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [15]:
m1 = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(m1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [16]:
a = np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


Создать 3x3 единичную матрицу

In [17]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Создать массив 3x3x3 со случайными значениями

In [18]:
b = np.random.rand(3,3)
print(b)

[[0.70427863 0.99899372 0.17360556]
 [0.70476396 0.66381599 0.9281571 ]
 [0.19852479 0.09036165 0.36367027]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [19]:
b = np.random.rand(30,1)
print(np.mean(b))

0.5046550703780294


Перемножить матрицы 5x3 и 3x2

In [9]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
c = a.dot(b)
print(c)


[[0.94640146 1.34003525]
 [1.19329735 1.61783325]
 [1.06079056 1.51368222]
 [1.13939109 1.59502822]
 [0.51374448 0.69833658]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [ ]:
a = np.

Заменить максимальный элемент на ноль

In [14]:
a = np.random.rand(10,1)
print(a)
a[np.argmax(a)] = 0.
print(a)

[[0.44880161]
 [0.45066775]
 [0.25999735]
 [0.11619064]
 [0.63278081]
 [0.64709801]
 [0.72361005]
 [0.75767592]
 [0.19949893]
 [0.83784456]]
[[0.44880161]
 [0.45066775]
 [0.25999735]
 [0.11619064]
 [0.63278081]
 [0.64709801]
 [0.72361005]
 [0.75767592]
 [0.19949893]
 [0.        ]]


Преобразовать массив из float в int

In [15]:
a = np.random.rand(10,1)
print(a)
a = a.astype(int)
print(a)

[[0.2367744 ]
 [0.1884805 ]
 [0.74038658]
 [0.27517283]
 [0.34603846]
 [0.57714937]
 [0.47346518]
 [0.87624444]
 [0.28857893]
 [0.26234985]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [26]:
def distance(x1,y1,x2,y2):
    return np.sqrt((x1-x2)**2 + (y1-y2)**2)
a = np.random.rand(10,2)*10
print(a)
b = np.zeros(100)
b = b.reshape(10,10)
print(b)
for i in range(10):
    for j in range(10):
        b[i,j] = distance(a[i,0],a[j,0],a[i,1],a[j,1])
print(b)

[[3.05923762 1.63840527]
 [6.49326542 4.74341311]
 [6.59115935 4.61870216]
 [7.39657247 7.78002382]
 [5.00849249 6.76276713]
 [3.71427655 2.98008733]
 [0.43265244 6.89886599]
 [1.77730429 5.39703086]
 [7.36772931 4.91235249]
 [7.81954396 0.25713961]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 2.00936038  2.25405139  2.43091586  1.47166555  2.25748623  1.59931185
   6.62047448  3.88859679  2.83683624  7.69472053]
 [ 2.25405139  2.47466487  2.63677273  1.79137323  2.4777939   1.89763456
   6.69879846  4.02049792  3.01510504  7.76221248]
 [ 2.43091586  2.63677273  2.7894757   2.00938356  2.63970962  2.10466652
   6.76036279  4.1222576   3.14951784  7.81540446]
 [ 1.47166555  1.79137323  2.00938356  0.54

Случайно расположить p элементов в 2D массив

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [45]:
a = np.array([1,2,3,4,5])
print(a)
for i in range(len(a)-1):
    a = np.insert(a,1+i*4,[0,0,0])    

print(a)

[1 2 3 4 5]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


Найти наиболее частое значение в массиве

In [30]:
a = np.random.randint(0,10,40)
print(a)
print(np.bincount(a).argmax())

[3 5 6 7 5 9 3 6 7 7 5 0 6 4 2 2 1 5 7 3 2 0 0 9 3 2 5 7 5 2 4 5 2 3 5 2 4
 5 4 4]
5


Найти n наибольших значений в массиве

In [32]:
n = 5
a = np.random.randint(0,100,20)
print(a[np.argsort(a)[-n:]])

[82 83 83 86 93]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [49]:
import pandas as pd
food = pd.read_csv('en.openfoodfacts.org.products.tsv',delimiter='\t',encoding='utf-8',low_memory=False)

Посмотреть первые 5 записей

In [50]:
food.head(5)

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity  ... fruits-vegetables-nuts_100g  \
0          NaN      1kg  ...                         NaN   
1          NaN      NaN  ...                         NaN   
2          NaN      NaN  ...                         NaN   
3          NaN      NaN  ...                         NaN   
4          NaN      NaN  ...                         NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [51]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [52]:
food.shape[1]

163

Напечатайте все названия столбцов

In [53]:
food.columns.values

array(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity', 'packaging', 'packaging_tags',
       'brands', 'brands_tags', 'categories', 'categories_tags',
       'categories_en', 'origins', 'origins_tags', 'manufacturing_places',
       'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en',
       'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo',
       'cities', 'cities_tags', 'purchase_places', 'stores', 'countries',
       'countries_tags', 'countries_en', 'ingredients_text', 'allergens',
       'allergens_en', 'traces', 'traces_tags', 'traces_en',
       'serving_size', 'no_nutriments', 'additives_n', 'additives',
       'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n',
       'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags',
       'ingredients_that_may_be_from_palm_oil_n',
       'ingredients_that_may_be_from_palm_oil',
   

Какое название у 105 столбца?

In [56]:
food.columns.values[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [58]:
food.dtypes[104]

dtype('float64')

Как проиндексирован набор данных?

In [61]:
print("don't understand question.")

don't understand question.


Каково значение имени продукта в 19-м наблюдении?

In [60]:
food.at[19,'product_name']

'Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [5]:
import pandas as pd
chipo = pd.read_csv('chipotle.tsv',delimiter='\t',encoding='utf-8')

Как много продуктов стоят более чем $10.00?

In [6]:
chipo['item_price_float'] = chipo[chipo.columns[4]].replace('[\$,]', '', regex=True).astype(float)
print(chipo[chipo['item_price_float'] > 10.00].shape[0])
#chipo.head(5)
#df.drop(['B', 'C'], axis=1)
#chipo=chipo.drop([5],axis=1)

#chipo.head(5)
#chipo.columns.values


1130


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [14]:
chipo[['item_name','item_price_float']]

item_name  item_price_float
0              Chips and Fresh Tomato Salsa              2.39
1                                      Izze              3.39
2                          Nantucket Nectar              3.39
3     Chips and Tomatillo-Green Chili Salsa              2.39
4                              Chicken Bowl             16.98
5                              Chicken Bowl             10.98
6                             Side of Chips              1.69
7                             Steak Burrito             11.75
8                          Steak Soft Tacos              9.25
9                             Steak Burrito              9.25
10                      Chips and Guacamole              4.45
11                     Chicken Crispy Tacos              8.75
12                       Chicken Soft Tacos              8.75
13                             Chicken Bowl             11.25
14                      Chips and Guacamole              4.45
15    Chips and Tomatillo-Green Chili Salsa              2.39
16                          Chicken Burrito              8.49
17                          Chicken Burrito              8.49
18                              Canned Soda              2.18
19                             Chicken Bowl              8.75
20                      Chips and Guacamole              4.45
21                         Barbacoa Burrito              8.99
22                         Nantucket Nectar              3.39
23                          Chicken Burrito             10.98
24                                     Izze              3.39
25             Chips and Fresh Tomato Salsa              2.39
26                             Chicken Bowl              8.49
27                         Carnitas Burrito              8.99
28                              Canned Soda              1.09
29                          Chicken Burrito              8.49
...                                     ...               ...
4592                       Barbacoa Burrito             11.75
4593                          Carnitas Bowl             11.75
4594                          Barbacoa Bowl             11.75
4595                           Chicken Bowl              8.75
4596                    Chips and Guacamole              4.45
4597                      Canned Soft Drink              1.25
4598                          Bottled Water              1.50
4599                           Chicken Bowl              8.75
4600                    Chips and Guacamole              4.45
4601                      Canned Soft Drink              1.25
4602                       Barbacoa Burrito              9.25
4603                       Barbacoa Burrito              9.25
4604                           Chicken Bowl              8.75
4605                    Chips and Guacamole              4.45
4606                      Canned Soft Drink              1.25
4607                          Steak Burrito             11.75
4608                         Veggie Burrito             11.25
4609                      Canned Soft Drink              1.25
4610                          Steak Burrito             11.75
4611                         Veggie Burrito             11.25
4612                          Carnitas Bowl              9.25
4613                                  Chips              2.15
4614                          Bottled Water              1.50
4615                     Chicken Soft Tacos              8.75
4616                    Chips and Guacamole              4.45
4617                          Steak Burrito             11.75
4618                          Steak Burrito             11.75
4619                     Chicken Salad Bowl             11.25
4620                     Chicken Salad Bowl              8.75
4621                     Chicken Salad Bowl              8.75

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [8]:
result = chipo.sort_values(['item_name'])


Сколько было заказано самого дорогого предмета?

In [9]:
#df['Age'].max()

#item_price_float
maxprice = chipo['item_price_float'].max()
print("maxprice = ", maxprice)
print(chipo[chipo['item_price_float'] == maxprice].shape[0])

maxprice =  44.25
1


Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [10]:
print(chipo[chipo['item_name'] == "Veggie Salad Bowl"].shape[0])

18


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [11]:
chipo.head(5)
print(chipo[(chipo['item_name']=="Canned Soda") & (chipo['quantity']>1)].shape[0])

20
